### ISSUE TITLE
Focus cards with a button instead of pressing a key

### ISSUE THREAD

**Issue by sillydomnom** [yduman/retro#117]
**Is your feature request related to a problem? Please describe.**
Currently there is a way to focus a card, but it is never shown that it is a possibility, neither how to do it. Moreover when typing a comment, it will result focusing some card when pressing the F key see #60.

**Describe the solution you'd like**
I would encourage to add an IconButton on the Card Header to focus a card. This Button will only be visible for the Moderator and others user may only see an Icon if the card is focused.

**Comment by yduman** [comment]
I agree with your proposed solution. This feature is really old and I believe even one of the first features. I don't really think that it was used at all, so feel free to implement your proposed solution. That way we highlight the "focus" feature and it will not interfere with the comment feature.

**Comment by yduman** [comment]
Resolved with 78aa40e3bd28d3636fb91c68e781930aa2219d05
