### ISSUE TITLE
Vote count can be set to negative numbers

### ISSUE THREAD

**Issue by MaikNog** [yduman/retro#42]
Vote count can be set to negative numbers .
Should go max. down to 0 Votes.

(Or is there a use case I am not aware of, that requires negative votes? 
Downvoting could be restricted, aka "Max. 3 downvotes", but that seems to me like a new feature and mostly not needed in typical retrospective circumstances)

**Comment by yduman** [comment]
Nice catch! Must've forgot it, when implementing it :) For now, the moderator should be aware, that this setting is nonsense ;) Will fix it, thank you!

**Comment by yduman** [comment]
fixed with dd9cba107776215676bc9e7ff6660ff58609894c
