### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by yduman** [yduman/retro#85]

**Comment by yduman** [comment]
@all-contributors please add mrpatpat for code

**Comment by yduman** [comment]
@all-contributors please add ClaasBusemann for code

**Comment by yduman** [comment]
@all-contributors please add PaulaBre for code

**Comment by yduman** [comment]
@all-contributors please add tobim-dev for code

**Comment by yduman** [comment]
@all-contributors please add ravensinth for code

**Comment by yduman** [comment]
@all-contributors please add 2mawi2 for code

**Comment by yduman** [comment]
done

**Comment by tobim** [comment]
I think you added the wrong tobim. Should have been @tobim-dev, not me.

**Comment by yduman** [comment]
Yeah I noticed that and fixed it manually in the PR. Sorry for that :)
